### ISSUE TITLE
kopi js date and time are wrong

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#114]
even though the order of the event is correct

![image](https://cloud.githubusercontent.com/assets/413879/5836300/bde609f8-a1ae-11e4-823b-0f404428e106.png)

**Comment by notthetup** [comment]
I suspect an iCal timezone issue.

**Comment by sayanee** [comment]
oooh the data is correct in the calendar - i think it's just the display

![image](https://cloud.githubusercontent.com/assets/413879/5839069/aa335b28-a1c6-11e4-8f49-28c709fb6eb0.png)

**Comment by sayanee** [comment]
looks like only the `formatted_time` is wrong upon querying the full api data:

```
{
id: "vjc0lgejuaslvsep6e8lir64pk",
name: "KopiJS 9th meetup",
description: "https://github.com/KopiJS/kopi.js/issues/20",
location: "Chin Mee Chin Confectionery, 204 East Coast Road, Singapore 428903",
url: "https://github.com/KopiJS/kopi.js/issues/20",
group_name: "KopiJS",
group_url: "http://kopi.io/",
formatted_time: "21 Jan 2015, Wed, 10:40 pm",
start_time: "2015-01-24T03:00:00.000Z",
end_time: "2015-01-24T06:00:00.000Z"
},
```
