### ISSUE TITLE
older than today events from eventbrite is coming up in the list

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#126]
![image](https://cloud.githubusercontent.com/assets/413879/6149901/e2a38b32-b246-11e4-9f90-8f7f7cec192a.png)

**Comment by sayanee** [comment]
temporarily blacklisted events that are older than today so that they don't appear d7f88966578f967c7acb37981712323c5fc9ef39

remove the blacklist events to start debugging.

**Comment by notthetup** [comment]
The issue is (surprise surprise!!) with Eventbrite API.

**Comment by notthetup** [comment]
The solution is to add another manual start-date filter.

**Comment by sayanee** [comment]
I thought we are already doing the filtering to keep only events from today onwards [here](https://github.com/webuildsg/webuild/blob/master/events/index.js#L126)

**Comment by sayanee** [comment]
or i guess we can add this filter for eventbrite events only

**Comment by notthetup** [comment]
That filter only get's applied to whiteListEvents. We should apply it to all events?

**Comment by sayanee** [comment]
maybe we just add on the eventbrite events for now :smile: that should work :+1:
