### ISSUE TITLE
title with emoji :thumbsup:

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#127]
like product-hunt's email in gmail

![screenshot 2015-02-20 12 00 49](https://cloud.githubusercontent.com/assets/413879/6281798/c6c5b986-b902-11e4-94d1-8f481c459671.png)

**Comment by sayanee** [comment]
http://stackoverflow.com/a/12115552/496797: `document.title = "We Build SG 🍞🍞"`

**Comment by sayanee** [comment]
what emojis would be fun and cool? 😉

![image](https://cloud.githubusercontent.com/assets/413879/6341849/8c3a4aba-bc0a-11e4-8fd6-9361b50f7713.png)

**Comment by notthetup** [comment]
:hankey:
