### ISSUE TITLE
weekly newsletter

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#128]
What do you all think about having a weekly newsletter? 

As a very simple start, every Sunday, a cron job will query the [event api endpoint](https://webuild.sg/api/v1/events) and gather the events for the next 7 days and send it to all subscribers.

**Comment by sayanee** [comment]
http://mailchimp.com/pricing/entrepreneur/ 

```
If you have fewer than 2,000 subscribers, you can send up to 12,000 emails per month absolutely free. No expiring trial, contract, or credit card required.
```

**Comment by notthetup** [comment]
SPAM!!! :-1:

**Comment by sayanee** [comment]
LOL but the users will subscribe / unsubscribe to it! :stuck_out_tongue_closed_eyes:

**Comment by cbas** [comment]
Maybe hook it up via [Customer.io](http://customer.io/)?

**Comment by sayanee** [comment]
Closed due to inactivity. Also, there are several clients being supported already.

Feel free to open with an implementation.
