### ISSUE TITLE
add tags for languages to each repo

### ISSUE THREAD

**Issue by lesterchan** [webuildsg/webuild#131]
Just submitting a new feature.
Example: http://github-awards.com/users?city=singapore&language=php&type=city

**Comment by notthetup** [comment]
*Cue language wars*.. *raises the ASM flag!!!*

**Comment by sayanee** [comment]
this is api endpoint url we need to query to get the language stats from github:

```
https://api.github.com/repos/webuildsg/webuild/languages
https://api.github.com/repos/{owner}/{repo}/languages
```

**Comment by sayanee** [comment]
Maybe we can start by populating the languages for each repo since the api endpoint from github already gives us the information. Then display them as "tags" on hover :stuck_out_tongue_closed_eyes:
