### ISSUE TITLE
admin panel to quickly remove / add events / groups

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#133]

**Comment by notthetup** [comment]
I would love to see how this could be done without needing a database. Maybe as an experiment.

**Comment by sayanee** [comment]
one idea:

using the [webuildsg-bot](https://github.com/webuildsg-bot) to commit to the files `config.js`, `blacklist`, `whitelist` as we are doing with [archives](https://github.com/webuildsg/webuild/blob/master/archives/index.js#L43-78)

**Comment by sayanee** [comment]
Closed due to inactivity. Feel free to open with a pull request to the code base.
