### ISSUE TITLE
"check for open events by date" not finding Hackware event

### ISSUE THREAD

**Issue by kaihendry** [webuildsg/webuild#135]
I was just about to book 8th of April but then I noticed there is an event already on the HSG calendar.

<img src=http://s.natalian.org/2015-03-09/events.png>

Sidenote: It would be nice if I could check the date in a GET request like:
https://check.webuild.sg/2015-04-08

And it would give a JSON response or something. Thanks!

**Comment by notthetup** [comment]
The API exists.. https://webuild.sg/api/v1/check/2015-04-08

**Comment by notthetup** [comment]
@kaihendry The issue here is we don't poll Hackerspace calendar for events, we get events from mainly Facebook, Meetup.com and Eventbrite. Adding Hackerspace calendar might add a lot of noise because of random other meetups.

**Comment by kaihendry** [comment]
I thought you supported ICS feeds? Noise can be filtered by someone checking for a clash, surely?

Anyway, Hackware I'm told is on Facebook & Meetup, so ... still there is an issue outstanding, no?

**Comment by notthetup** [comment]
@kaihendry Issue isn't ICS feeds, but if we want to pick up Hackerspace feed. I don't understand how one can filter out events like "Ukulele meetup" by checking for clashes (which btw is already happening).

Hackware is on FB/Meetup but I guess they haven't created an event for April? I think this issue should be in their bucket.

**Comment by Nexus7** [comment]
Maybe I'll create the placeholders for Hackware for the rest of the year in meetup.com... we try and stick to 2nd Wednesday of each month...

**Comment by notthetup** [comment]
Sure. That works.

**Comment by Nexus7** [comment]
Done.
