### ISSUE TITLE
handle error if ics url is not available

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#142]
example: 

```
Here is the 1 recent event matching your Error search.

Mar 16 09:42:33 webuildsg app/web.1: Error: Reading ICS Group from SG Hack & Tell: Error: connect ETIMEDOUT 
```

**Comment by kaihendry** [comment]
You have an error message... what more do you want? :)

**Comment by notthetup** [comment]
Agreed! The error should be caught and logged (as done above). The only thing to confirm is that one ICS calendar retrieving/praising throwing and error doesn't call all other ICS calendars to not load.
