### ISSUE TITLE
better error message instead of "Invalid date"

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#143]
Go to [checker](https://webuild.sg#checker):

![image](https://cloud.githubusercontent.com/assets/413879/6665878/bd199b94-cc19-11e4-9d0d-ab64e8cee13a.png)

it should not say `Invalid date` when there is no entry

**Comment by kaihendry** [comment]
Still says invalid date for me https://s.natalian.org/2017-05-02/1493688487_2558x1408.png

**Comment by sayanee** [comment]
@kaihendry could you provide the following information:

1. Operating System and version
1. Browser and version
1. Browser console errors and you try to query with the date

Thanks 🙏

**Comment by notthetup** [comment]
Relevant code https://github.com/webuildsg/webuild/blob/master/public/js/lib/check.js#L25
