### ISSUE TITLE
duplicate events getting wrongly removed

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#146]
2 events at same time, same location, but different rooms - one of them is getting deleted. check by `event.name` only

1. [talk.js](http://www.meetup.com/Singapore-JS/events/221079427/)
- [windows phone user group](http://www.meetup.com/mssgug/events/221075589/)

**Comment by notthetup** [comment]
Ha ha! I think the overlap algorithm needs a bit more 'fuzzy logic'

**Comment by sayanee** [comment]
yeah... for now I will just remove the location check... let's think more about the AI, which inevitably means more data :1234:
