### ISSUE TITLE
Some events span multiple days by accident, flooding iCal

### ISSUE THREAD

**Issue by Valentine** [webuildsg/webuild#148]
Example: http://www.eventbrite.sg/e/future-of-health-tickets-16336243143

![screen shot 2015-03-31 at 5 02 04 am](https://cloud.githubusercontent.com/assets/676061/6906725/224fddc6-d763-11e4-9ab9-46085819af9f.png)

**Comment by notthetup** [comment]
Hmm.. Maybe the solution is to have a max length on an event? But what could that be? 2/3days?

**Comment by Valentine** [comment]
3 days sounds good! Covers 99% of the conferences out there. You could just display the start date if it's longer.

**Comment by notthetup** [comment]
We usually don't pick up conferences since most aren't free.

**Comment by sayanee** [comment]
which email client are you using @Valentine? With GCal it looks pretty clean:

![image](https://cloud.githubusercontent.com/assets/413879/6916449/02d65b20-d7cf-11e4-959a-ae62d906db5b.png)

**Comment by Valentine** [comment]
That's because GCal has the sense to separate multiple day events lah! It looks pretty cluttered in GCal's monthly view too:
![screen shot 2015-03-31 at 6 26 12 pm](https://cloud.githubusercontent.com/assets/676061/6917021/728af06c-d7d3-11e4-908e-6208351051ef.png)

**Comment by sayanee** [comment]
We have informed the event organizer to amend the date and time. We don't change our code as it is very rare to have month long free events.

Will leave this open until the original event is fixed.
