### ISSUE TITLE
retro hipster desktop mac app

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#153]
with [macgap](https://github.com/MacGapProject) or [node webkit](https://github.com/nwjs/nw.js/#introduction) or [atom shell](https://github.com/mafintosh/atom-shell)?

**Comment by notthetup** [comment]
WHAI?? Web Platform FTW!

**Comment by sayanee** [comment]
just for fun to learn how to do desktop app? :laughing: and maybe integrate things that can be done only with desktop apps?

**Comment by notthetup** [comment]
If you wanna make real desktop apps, then you can learn how to make. Making 'Desktop apps' with nw or atom shell is just hipster.. :stuck_out_tongue:

**Comment by cbas** [comment]
Hipster? More like retro.

https://github.com/pandion/pandion/tree/master/Host

**Comment by sayanee** [comment]
thought a menubar os x app might be way better: https://github.com/webuildsg/osx#webuild-sg-menubar
