### ISSUE TITLE
hubot script for gitter and irc

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#156]
using https://github.com/hubot-scripts like slack integration https://api.blockspring.com/cheeaun/webuildsg-slack

![screenshot_2015-04-15_13_33_54](https://cloud.githubusercontent.com/assets/413879/7152911/cec744ee-e376-11e4-86f1-f699bb808d27.jpg)

**Comment by cheeaun** [comment]
:+1:

**Comment by alyssaq** [comment]
:+1:

**Comment by sayanee** [comment]
Closed due to inactivity. Feel free to open with a pull request to the code base / implementation.

Maybe YAGNI too?
