### ISSUE TITLE
Tech In Asia feed

### ISSUE THREAD

**Issue by cbas** [webuildsg/webuild#159]
@terenceleejx Terence Lee from Tech In Asia via Facebook Messenger:
> Hi Sebastiaan, I'm Terence from Tech in Asia. I noticed that you're running the Front End TL;DR event. I'd like to encourage you to try out our Facebook event submission feature. Just key in the URL and you're done. You can do this for future events you organize too. Your event will get exposed to TIA's audience. Do let me know how this might be more useful for you! https://www.techinasia.com/tech-startup-events/community/add

This is unacceptably manual. I feel like they can already use the Webuild API v1 [`/events`](https://webuild.sg/api/v1/events) endpoint to automate it. Just wanted to create this issue to discuss:

1. Pushing events from Webuild to TIA's registry. (Not a fan of this but it's an option.)
1. Feedback on the Webuild API from Tech In Asia should there be a follow up conversation.

**Comment by notthetup** [comment]
:+1:

**Comment by sayanee** [comment]
Yes there's already an api endpoint. Closing this issue as no code changes are required. Feel free to re-open after any discussion with TIA.
