### ISSUE TITLE
GEVME

### ISSUE THREAD

**Issue by cbas** [webuildsg/webuild#160]
Is this a new event organising platform? Just saw it used for UXSG:
https://www.gevme.com/uxsg-meetup-14-open-space

**Comment by notthetup** [comment]
Dammit these hipsters and these new fangled platforms without APIs!!

**Comment by sayanee** [comment]
web scrap it!

**Comment by sayanee** [comment]
For now we can manually add the events in `events/whiltelistEvents.json`. Let's observe the trend - if there are too many, we should web scrap the url.

Feel free to open when there are at least 1 event / month from this platform.
