### ISSUE TITLE
venue info in Slackbot

### ISSUE THREAD

**Issue by chernjie** [webuildsg/webuild#163]
![image](https://cloud.githubusercontent.com/assets/275729/7743571/b4549264-ffce-11e4-8b9c-e9b966711b39.png)

It would be nice if it can show venue information as it is already available in the [API](https://webuild.sg/api/v1/events)

**Comment by sayanee** [comment]
:+1:

**Comment by sayanee** [comment]
@chernjie can close? :stuck_out_tongue_closed_eyes: 

![image](https://cloud.githubusercontent.com/assets/413879/7744439/c2879136-ffd5-11e4-9a0d-0e6e372b11ae.png)

thanks @cheeaun :heart_decoration:
