### ISSUE TITLE
new api endpoints /events/today, /events/tomorrow, events/hour, events/:num

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#164]
new api endpoints to cater for various plugins (slack bot, menubar app, cli, etc)

1. `/api/v1/events/today` - give a list of events starting today before `11:59pm`
- `/api/v1/events/tomorrow` - give a list of events starting tomorrow before `11:59pm` tomorrow
- `/api/v1/events/hour` - give a list of events starting within the next hour
- `/api/v1/events/:num` - give a list of `num` number of upcoming events

**Comment by sayanee** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by sayanee** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by notthetup** [comment]
Why can't clients do this filtering? YAGNI?

**Comment by sayanee** [comment]
The 4 clients we have now - slackbot, cal, frontend, menubar are all requiring these info. So it's not YAGNI.
