### ISSUE TITLE
Enable CORS in the API

### ISSUE THREAD

**Issue by cheeaun** [webuildsg/webuild#165]
Because [CORS](http://enable-cors.org/) rocks.

**Comment by sayanee** [comment]
:+1:

**Comment by sayanee** [comment]
thanks @notthetup @cheeaun :tada: pushed to production ❤️💙💚💛💜

![image](https://cloud.githubusercontent.com/assets/413879/8020054/d0032d78-0c9d-11e5-9d65-a7c877c41f50.png)

**Comment by cheeaun** [comment]
:+1:
