### ISSUE TITLE
Unicode characters not shown properly in Google Calendar

### ISSUE THREAD

**Issue by soareschen** [webuildsg/webuild#167]
![screenshot from 2015-06-05 23 00 14](https://cloud.githubusercontent.com/assets/97665/8008893/8cdf59de-0bd7-11e5-82e2-4b53e76083fa.png)

The affected meetup is http://www.meetup.com/Japanese-Engineers-in-Singapore/events/222590136/

**Comment by notthetup** [comment]
So the is it an iCal issue?? http://webuild.sg/cal

**Comment by notthetup** [comment]
Seems like not. The iCal files seems to be generated correctly.

![screenshot 2015-06-05 23 10 24](https://cloud.githubusercontent.com/assets/553140/8008979/1deb0338-0bd8-11e5-9f2e-cada1906f1c3.jpg)

**Comment by notthetup** [comment]
So is this a Google Calendar issue?

**Comment by sayanee** [comment]
Seems like it's GCal. No solutions yet? 

- [from the forum](https://productforums.google.com/forum/#!topic/calendar/Ddk9kHA7O0c)

**Comment by cheeaun** [comment]
Looks like the file is served with `Content-Type: text/calendar`. Probably can try `Content-Type: text/calendar; charset=UTF-8`?

**Comment by notthetup** [comment]
OK. I can try.

**Comment by sayanee** [comment]
just put it in a branch and `git push staging master` 🎈

**Comment by notthetup** [comment]
OK. That `charset` seems to work. I have a testing build at http://webuildsg-dev.herokuapp.com. Sadly it doesn't pick up the older events anymore. :(

**Comment by sayanee** [comment]
thanks @soareschen @notthetup @cheeaun! pushed production :tada: 

![image](https://cloud.githubusercontent.com/assets/413879/8020062/07625302-0c9e-11e5-9347-74914953479d.png)
