### ISSUE TITLE
a section to list all the apps

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#170]
Example `webuild.sg#apps` or `webuild.sg/apps` to list:

1. calendar with iCal / gCal
- command line
- slackbot
- OS X Menubar
- iPhone
- Google Chrome extension
- Firefox Extension
- IFTTT Maker channel
- Android

Different ways, but same info :dancer:

**Comment by sayanee** [comment]
design inspiration from [slack integration page](https://slack.com/integrations):

1. 2 columns
- icon of the app
- a little description
- link to install / instructions
- a search bar

**Comment by cheeaun** [comment]
A good reference: https://readability.com/apps

**Comment by sayanee** [comment]
exactly so  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by sayanee** [comment]
inspiration from:

Slack:

![screenshot 2015-06-11 10 03 21](https://cloud.githubusercontent.com/assets/413879/8123916/905b7c14-1104-11e5-9dd4-a0063d3b25a6.png)

Readability:

![image](https://cloud.githubusercontent.com/assets/413879/8123923/a6286da4-1104-11e5-8e12-a8da3b107ea5.png)

**Comment by sayanee** [comment]
![image](https://cloud.githubusercontent.com/assets/413879/13560403/ad1a403c-e459-11e5-9d42-8ed7b45dcff5.png)

**Comment by cheeaun** [comment]
:thought_balloon: Probably need some CTA buttons there.

- "Download" for the apps
- "Subscribe" for the calendar
- "Add to Slack" for the slack one

**Comment by sayanee** [comment]
Good idea! 

I'm currently hyperlinking the [entire section](https://github.com/webuildsg/webuild/blob/master/views/apps.jade#L33-L39). Instead of that, put in a smaller button like Readability, I guess.

![image](https://cloud.githubusercontent.com/assets/413879/13560788/c3ba9710-e45e-11e5-99e2-e8d34b081a55.png)

**Comment by cheeaun** [comment]
Actually can still hyperlink the enter section, just need to add button inside :smile:

**Comment by sayanee** [comment]
:dancer: :dancers: on it!

**Comment by sayanee** [comment]
![image](https://cloud.githubusercontent.com/assets/413879/13561096/a7e26d88-e463-11e5-9dfc-9095bc74960d.png)

**Comment by cheeaun** [comment]
:+1: :+1: :+1:
