### ISSUE TITLE
"handpicked"

### ISSUE THREAD

**Issue by cbas** [webuildsg/webuild#177]
Repo description says "handpicked" but I think "Robothandpicked" is more accurate.

![Webuild repo description screenshot](https://cloud.githubusercontent.com/assets/78718/8792373/12276a20-2f99-11e5-8261-fd8f53a539e8.png)

**Comment by notthetup** [comment]
"Hand-built robot"-picked.

**Comment by sayanee** [comment]
:heart_eyes: 

![image](https://cloud.githubusercontent.com/assets/413879/8816422/67585c78-3059-11e5-8b2a-d97aba268538.png)

**Comment by uzyn** [comment]
:+1: as long as the robot does not escape the box. http://www.yudkowsky.net/singularity/aibox/
