### ISSUE TITLE
Hacks & Hackers

### ISSUE THREAD

**Issue by cbas** [webuildsg/webuild#178]
Any idea why events from this meetup group are not being listed?

http://www.meetup.com/Hacks-Hackers-Singapore

**Comment by cbas** [comment]
OIC https://github.com/webuildsg/webuild/blob/master/config.js#L129

Any idea why they were blacklisted?

**Comment by alyssaq** [comment]
The upcoming event sounds pretty cool

**Comment by notthetup** [comment]
Because their previous meetups were "Monthly Drinks with Online News Association Singapore Chapter"

**Comment by sayanee** [comment]
thanks for the alert @cbas! pushed it production :tada: 

![image](https://cloud.githubusercontent.com/assets/413879/8816170/b8798c84-3055-11e5-817f-bba54d64cd14.png)

**Comment by cbas** [comment]
:+1: Yay!
