### ISSUE TITLE
Safari / FireFox datepicker bug

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#182]
http://caniuse.com/#search=input-date

![image](https://cloud.githubusercontent.com/assets/413879/9055067/d9e09098-3ab9-11e5-9c04-a65e4dc1b59b.png)

**Comment by notthetup** [comment]
FF also same.. This is only supported by Chrome!

Love live Web 'Standards'!

**Comment by sayanee** [comment]
Firefox:

![image](https://cloud.githubusercontent.com/assets/413879/9055135/54f55a48-3aba-11e5-9d36-ca4cc8b2c22a.png)
