### ISSUE TITLE
Openshift app doesn't restart everytime after a git push. 

### ISSUE THREAD

**Issue by notthetup** [webuildsg/webuild#185]
After git push the gear tries to run a new instance and which throws an EADDRESSINUSE error, which indicates that the previous instance of the app wasn't killed properly.

Relevant reading.. https://docs.openshift.org/origin-m4/oo_cartridge_developers_guide.html#openshift-builds

**Comment by sayanee** [comment]
temporary workaround is to force stop and then re-deploy:

```
rhc app-force-stop --app production
rhc deploy master -a production
```

**Comment by sayanee** [comment]
run `npm run deploy`
