### ISSUE TITLE
Missing repos

### ISSUE THREAD

**Issue by cbas** [webuildsg/webuild#187]
Where is the code for these?
https://www.npmjs.com/package/webuild-repos
https://www.npmjs.com/package/webuild-events

**Comment by notthetup** [comment]
https://github.com/webuildorg/webuild-events and https://github.com/webuildorg/webuild-repos

Updated the package.json

**Comment by sayanee** [comment]
closed with 81859aa029f365432e6fca651e5a5f468d2fc4d7 and f2457e5069ff6cae5d70e5a3ba38765140d42e0d
