### ISSUE TITLE
www.webuild.sg is not redirecting to https://webuild.sg

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#201]
thanks @kaihendry 🤗

![image](https://cloud.githubusercontent.com/assets/413879/13274935/7e7e0e66-daea-11e5-9247-4dd7cfb6dd6c.png)

**Comment by notthetup** [comment]
Fixed! When re-creating instances in OpenShift, we need add alias for both `www.webuild.sg` and `webuild.sg`.

![screenshot 2016-02-24 12 14 13](https://cloud.githubusercontent.com/assets/553140/13275448/3a3f458e-daf0-11e5-976f-bf9b9360911a.jpg)

**Comment by kaihendry** [comment]
http://s.natalian.org/2016-02-24/1456288323_1048x1036.png
 
Bit slow, no?

**Comment by notthetup** [comment]
@kaihendry If you have a better solution please recommend.
