### ISSUE TITLE
custom 503 error page stating it's deploying

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#202]
- [how to set a custom error page in open shift](https://openshift.uservoice.com/forums/258655-ideas/suggestions/6291291-custom-error-templates)
- [cartridge for maintenance page](https://github.com/mignev/openshift-cartridge-maintenance-page)

![image](https://cloud.githubusercontent.com/assets/413879/13306859/1b3ec3be-dba2-11e5-99a9-ba19d39630fb.png)

**Comment by notthetup** [comment]
This seems to work. But we will need to fork the repo and make a custom 503 page.

![screenshot 2016-07-24 16 32 06](https://cloud.githubusercontent.com/assets/553140/17082782/32db73d8-51bc-11e6-862c-9942112b15cf.jpg)

**Comment by notthetup** [comment]
custom page!

![image](https://cloud.githubusercontent.com/assets/553140/17082820/78c82f0c-51bd-11e6-985d-2ff4362589f4.png)

**Comment by sayanee** [comment]
maintenance page cartridge can be found here: https://github.com/webuildsg/openshift-cartridge-maintenance-page

**Comment by notthetup** [comment]
Done!

![Uploading image.png…]()
