### ISSUE TITLE
Product Design Singapore group is not being picked up with meetup.com api

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#203]
Why? :sob: 

Search on [api console](https://secure.meetup.com/meetup_api/console/?path=/2/groups) with `group_urlname` as **Product-Design-Singapore**

![image](https://cloud.githubusercontent.com/assets/413879/13420613/bf25f15e-dfc2-11e5-94bb-180f5e2d8b74.png)

**Comment by notthetup** [comment]
Must be getting filtered out because of some word in their description.

**Comment by sayanee** [comment]
No - i did a `console.log` before [this line](https://github.com/webuildorg/webuild-events/blob/master/events/meetupEvents.js#L32) 😅 *hhmmm*

**Comment by sayanee** [comment]
Doing a manual api search for `/2/groups` with params from [config.js](https://github.com/webuildsg/webuild/blob/0e8a60c098d66ed6b4af8874b632b43373c81d96/config.js#L76-L83):

![image](https://cloud.githubusercontent.com/assets/413879/13560756/30d75708-e45e-11e5-8c4f-cea6b15ba199.png)

**Comment by sayanee** [comment]
related to #219
