### ISSUE TITLE
sample configuration files for setting up the various environments

### ISSUE THREAD

**Issue by juslee** [webuildsg/webuild#207]
Where do we put sample config files to set up on OpenShift, Heroku and Bluemix?

**Comment by sayanee** [comment]
Here are the [conf files for openshift](https://github.com/webuildsg/webuild/tree/master/.openshift)

What extra files / folder structure would you need for heroku and bluemix?

**Comment by juslee** [comment]
I just need to add the manifest.yml for bluemix to set up. I'm not sure about heroku. Check #206 for the updated documentation.

**Comment by sayanee** [comment]
Thanks! Since this repository is used for the actual production deployment on Openshift, let's add to the docs for Heroku and Bluemix deployment and not the code?

**Comment by juslee** [comment]
Usually these configs are located at docs/sample_config directory or something. But if you're good with the docs then it's all good.

**Comment by sayanee** [comment]
Uh! the Heroku deployment instructions are already in the doc, but yes the code like the `Procfile` was removed as this repository is not deployed to Heroku anymore. But docs can remain of course 🤗like how you are adding Bluemix now.

**Comment by juslee** [comment]
Alright. Please check #206. It wasn't too difficult to deploy on Bluemix. I've yet to figure out the cron jobs yet.

**Comment by sayanee** [comment]
closed with #206

Will add a note that **This repository contains the deploy code for OpenShfit**
