### ISSUE TITLE
cron job is being triggered twice 

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#208]
https://github.com/webuildsg/data/issues/52

**Comment by notthetup** [comment]
Seems like it commits to `gh-pages` or `staging` branch based on the environment.

https://github.com/webuildsg/webuild/blob/c2f5f1cb8016bbd3c47c1baa219c48154423ccce/archives/index.js#L9

**Comment by sayanee** [comment]
yeah... i totally skipped archival if `NODE_ENV` is not `production` for now :laughing: 

no `json` files were being pushed to `staging` branch either

**Comment by sayanee** [comment]
closed with https://github.com/webuildsg/data/issues/52
