### ISSUE TITLE
create a new repository for api.webuild.sg for self-documenting webuild.sg api endpoints

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#210]
- [x] new subdomain `api.webuild.sg`
- [x] [remove from docs](https://github.com/webuildsg/webuild#api-endpoints) and link it to `api.webuild.sg`
- [ ] amend all headers to include this link to `api.webuild.sg`

Inspiration: [api.github.com](https://api.github.com/)

![image](https://cloud.githubusercontent.com/assets/413879/13527252/c924db06-e248-11e5-9ca9-987d38aa7931.png)

**Comment by juslee** [comment]
I think the new subdomain should be api.webuild.sg not api.github.com right?

**Comment by sayanee** [comment]
thanks @juslee - corrected 😄 and it's available now https://api.webuild.sg

Could you give links to examples to existing API platforms where loopback and swagger for the APIs were implemented so that I can pick up and look at some best practices?

**Comment by sayanee** [comment]
https://github.com/webuildsg/data/commit/e4a67aa7a535a23934bc5fba57130c0cb760ae4e

**Comment by sayanee** [comment]
https://github.com/webuildsg/live/commit/e64fd538ac7e1dbf8a906fcce7ce991f476be5ed

**Comment by sayanee** [comment]
https://github.com/webuildsg/notes/commit/c0bda180f7e25b92c06aab79aa2e68335ea2cebd

**Comment by sayanee** [comment]
https://github.com/webuildsg/notes/commit/c0bda180f7e25b92c06aab79aa2e68335ea2cebd
