### ISSUE TITLE
Magento Meetup not on the list.

### ISSUE THREAD

**Issue by miccheng** [webuildsg/webuild#219]
http://www.meetup.com/Singapore-Magento-User-Group/events/230192978/

**Comment by sayanee** [comment]
thanks for the heads up @miccheng!

**Comment by sayanee** [comment]
Sent email to `support@meetup.com` and included the meetup temporarily as part of whitelist events.

**Steps to reproduce**

1. Go to web console and fill in the params: https://secure.meetup.com/meetup_api/console/?path=/2/groups

  ![image](https://cloud.githubusercontent.com/assets/413879/14452805/b1342c42-00c3-11e6-8da5-5435aa0e310d.png)
- Find `Singapore Magento`

  ![image 1](https://cloud.githubusercontent.com/assets/413879/14452814/c019089a-00c3-11e6-85e4-31836de81e6e.png)
- Run the same query with node.js file:

  ```js
var request = require('request')

request('https://api.meetup.com/2/groups?key=82720666d13c787d8292c5d12335d&country=SG&city=Singapore&category_id=34&page=1000&fields=next_event&', function (error, response, body) {
  if (!error && response.statusCode == 200) {
    var data = JSON.parse(body).results

    data.forEach(function(d) {
      console.log(d.country, d.id, d.category.id, d.city, d.name)

      if (d.name.toLowerCase().includes('magento')) {
        console.log('Found Singapore Magento user group :)')
      }
    })
  }
})
  ```

**Expected outcome**

- Singapore Magento group is part of the results

**Actual outcome**

- Singapore Magento is not part of the results

**Comment by hboon** [comment]
I noticed there's exactly 200 results. Pagination?

**Comment by sayanee** [comment]
@hboon thanks! Interesting I did not notice that. Maybe I should read up more on what `page: 1000` does, or maybe another param that I should fill up to get all results instead of just 200.

**Comment by kahwee** [comment]
@hboon is right.

Need to request offset 0:

```
https://api.meetup.com/2/groups?key={SECRET}&country=SG&city=Singapore&category_id=34&page=200&offset=0&fields=next_event
```

And offset 1:

```
https://api.meetup.com/2/groups?key={SECRET}&country=SG&city=Singapore&category_id=34&page=200&offset=1&fields=next_event
```

The change in the URL is `page=200&offset=0`

Anyone want to take this up?

**Comment by sayanee** [comment]
Big thanks @hboon and @kahwee - I will add `offset: 0` as part of the meetup.com config here https://github.com/webuildsg/webuild/blob/e95b60dc9b445e584ba3b9ebfb2a5d558573524e/config.js#L111-L118

**Comment by hboon** [comment]
Hmm.. Does it automatically make multiple calls using an increasing value of `offset` like  @kahwee mentioned?

**Comment by sayanee** [comment]
eeeks! Yes, it does not make multiple calls with `offset=0` and then `offset=1`.

But how many `offset` we need to make? Why stop at `1`? Trying to set to the API docs to know what is `offset`

**Comment by sayanee** [comment]
Here's the doc: http://www.meetup.com/meetup_api/docs/2/groups/, but it doesn't explain `offset`

**Comment by sayanee** [comment]
But here's the answer when we set `offset=1` :smile: 

```
Found 27 Meetup.com groups
SG 19432258 34 Singapore DevSecOps Singapore
SG 19443672 34 Singapore 9goTech - Technology Start-Up & Innovation Symposium
SG 19482908 34 Singapore Singapore Smart Home & Intelligent Property Meetup
SG 19488686 34 Singapore Singapore Magento User Group
Found Singapore Magento user group :)
SG 19529162 34 Singapore School of Startup
SG 19529569 34 Singapore Singapore Cybersecurity Meetup
SG 19542112 34 Singapore Old group. Go here: http://www.meetup.com/BitcoinSingapore/
SG 19542429 34 Singapore Singapore from PhD to Startup
SG 19543645 34 Singapore HR Analytics Singapore
SG 19550420 34 Singapore SG Web Programming Workshop
SG 19562531 34 Singapore Singapore Game Apps Design And Development
SG 19564435 34 Singapore Citizen Maker Movement
SG 19593085 34 Singapore Singapore Full Stack Developer
SG 19617994 34 Singapore Product Design Singapore
SG 19623244 34 Singapore Jenkins User Group Singapore
SG 19624588 34 Singapore AppDynamics Singapore User Group
SG 19676036 34 Singapore Singapore Algorithmic Trading Meetup
SG 19690706 34 Singapore Future of Data: Singapore
SG 19705933 34 Singapore Singapore SDN & NFV Meetup
SG 19722112 34 Singapore Singapore Social Engineers Hangout
SG 19738071 34 Singapore HyperLedger (Singapore Chapter)
SG 19754453 34 Singapore Firebase Meetup (South East Asia)
SG 19756671 34 Singapore Greater Singapore Cyber Security for Controls Systems
SG 19768239 34 Singapore Fedora in Singapore
SG 19770265 34 Singapore Singapore Djangonauts
SG 19792372 34 Singapore Singapore Data Science Course (For Beginners)
SG 19838679 34 Singapore SAP Professional Group
```

**Comment by hboon** [comment]
Looks good :)
