### ISSUE TITLE
We Build Messenger Facebook bot

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#220]
We Build FB Messenger bot should be fairly easy as we will just start by having options to list the **five** upcoming events and recently updated repositories.

Drop us a note below if you want to try out building a messenger bot 🤗

- **Docs:** https://messengerplatform.fb.com/
- **Facebook page**: https://www.facebook.com/webuildsg
- **Open API endpoints:** https://api.webuild.sg/

**Comment by kahwee** [comment]
I could pick this one up. I'm interested to try this out. And hello there @sayanee!

**Comment by sayanee** [comment]
thanks @kahwee :smiley: Will add you as `admin` in Facebook!

**Comment by kahwee** [comment]
By the way, there's also an approval process for Facebook to vet the bot.

**Comment by sayanee** [comment]
Sure! Just like iOS apps? We will go through them :+1:

**Comment by alyssaq** [comment]
Woot. This is gonna be an interesting lil project for webuild!

**Comment by kahwee** [comment]
Do we have a privacy policy URL somewhere? Facebook requires this.

If we do not have this document, who is best to advice on this?

**Comment by sayanee** [comment]
Privacy Policy. Hhhmmm. No we don't. Is there a good template / guideline we can pick from like open source licenses? I'm cool with a simple and good one.

**Comment by sayanee** [comment]
Eeek! I realised there's no easy way to generate / google / github templates for a simple Privacy Policy. 

Well, the data collected by We Build SG is all through public APIs and no private user data is collected as there's login at all.

**Comment by kahwee** [comment]
I think we can try this: https://termsfeed.com/privacy-policy/generator/

**Comment by kahwee** [comment]
I take that back. It needs you to pay for many of the options. I try to use [this](https://www.freeprivacypolicy.com)

But that's not entirely Singapore specific.

I'll open another issue specific to privacy policy.

**Comment by kahwee** [comment]
I can't seem to transfer https://github.com/kahwee/bot to `webuildsg` (need admin). I added @sayanee as collaborator. I'm not sure if this allows transfer.

**Comment by kahwee** [comment]
FYI

> During the current beta period, the onboarding for the Messenger platform is limited to ensure the best user experience. Please be patient and check your dev alerts for updates; the approval may take up to several weeks. To make changes to this submission, click the Cancel Submission button.

**Comment by sayanee** [comment]
:tada: transfer future discussions here :heart:
