### ISSUE TITLE
plot bar graph to visualise the number of meetups in the coming 14 days

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#228]
Sometimes there are days with 1 / no meetups and these are golden opportunities for organisers to hold their meetups then. 

![image](https://cloud.githubusercontent.com/assets/413879/15202546/12702a0c-182e-11e6-85e9-ccc9dc23633b.png)

![image](https://cloud.githubusercontent.com/assets/413879/15202605/786de8e4-182e-11e6-8cd9-ef4457ac07b2.png)

Design inspiration from Github's [Commit activity](https://github.com/webuildsg/webuild/graphs/commit-activity):

![image](https://cloud.githubusercontent.com/assets/413879/15202562/2f5ee0f4-182e-11e6-8119-b7d18aeb1322.png)

**Comment by sayanee** [comment]
cc @miccheng @cheeaun what do you all think? Just another tiny visualisation to help meetup organisers see which are the upcoming light days to organise meetups.

**Comment by miccheng** [comment]
Would be nice. But it doesn't help you with making a decision on which meetup to attend. For meetup organizers, it might be helpful.

**Comment by sayanee** [comment]
@miccheng yes it's for meetup organisers, not for meetup attendees.

**Comment by sayanee** [comment]
with d3.js https://bost.ocks.org/mike/bar/3/

**Comment by sayanee** [comment]
initial look and feel:

![image](https://cloud.githubusercontent.com/assets/413879/17082106/7a3ad114-51a4-11e6-8bbd-af0186d122fd.png)

**Comment by sayanee** [comment]
with real data:

![image](https://cloud.githubusercontent.com/assets/413879/17141623/4e21738a-537f-11e6-9f70-842ccb77a101.png)

**Comment by cheeaun** [comment]
Probably can bold the **today** date?

**Comment by kahwee** [comment]
It will be pretty cool if the weekends are of a different shade!

**Comment by sayanee** [comment]
@kahwee great minds think alive? 😅 yups was thinking of that too!

@cheeaun roger!

**Comment by sayanee** [comment]
ok i ship to production this version first, so that organisers can start using it. Will work on the weekends, bold and some hover styles soon for iteration. Also let's see what the community needs as well 🎉

**Comment by miccheng** [comment]
![screen shot 2016-07-27 at 11 33 34 am](https://cloud.githubusercontent.com/assets/211980/17163055/0bba08b2-53ee-11e6-81da-114e9e274e46.png)

Did u test this in Safari?

**Comment by sayanee** [comment]
@miccheng try clear cache? `shift + cmd + R`

**Comment by cheeaun** [comment]
@sayanee use XHR instead of `fetch` 😛

**Comment by miccheng** [comment]
Safari uses a diff command. But even after clearing cache, its still showing the same error.

**Comment by notthetup** [comment]
https://github.com/github/fetch should work on Safari.

**Comment by sayanee** [comment]
@cheeaun making too many XHR already for `GET` and `POST`... might as well use the `fetch` library now. Anyway, it's gonna be soon that browsers will implement it natively? When?

**Comment by sayanee** [comment]
@miccheng so this error was on Safari? ok noted

**Comment by sayanee** [comment]
😱 😅

![image](https://cloud.githubusercontent.com/assets/413879/17163185/38a3169c-53ef-11e6-8c4a-b0d2cca01644.png)

**Comment by sayanee** [comment]
@notthetup ok added to the tweaks for Safari https://github.com/webuildsg/webuild/issues/228#issuecomment-235472394 Thanks @miccheng 😍

**Comment by miccheng** [comment]
Anytime...

**Comment by cheeaun** [comment]
@sayanee I'm still not seeing `fetch` in latest Safari Technology Preview, but got news that it will be supported in next version soon.

**Comment by sayanee** [comment]
@cheeaun let's see https://github.com/github/fetch/issues/303 🤔

**Comment by notthetup** [comment]
That's Safari's Tech Preview issue. If it implements and then BREAKS `fetch` they can go and die.

**Comment by sayanee** [comment]
mark **today** and lighter colored weekend columns:

![image](https://cloud.githubusercontent.com/assets/413879/17215591/fa7eb2fa-550f-11e6-823f-d584e2d51f19.png)

**Comment by sayanee** [comment]
🎉 

![image](https://cloud.githubusercontent.com/assets/413879/17220269/1dcfce5e-5521-11e6-949a-68083ee1a4c1.png)
