### ISSUE TITLE
upgrade Auth0 library

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#229]
![image](https://cloud.githubusercontent.com/assets/413879/15203139/568ada16-1833-11e6-84d7-1c0f7078f91a.png)

**Comment by notthetup** [comment]
Seems like we're using `"auth0-widget.js": "5.2.13"` from bower. And appreantly it's deprecated. We should move to https://www.github.com/auth0/lock

**Comment by notthetup** [comment]
https://auth0.com/docs/libraries/lock

**Comment by sayanee** [comment]
![image](https://cloud.githubusercontent.com/assets/413879/17076684/31556928-50eb-11e6-9065-82d3353f7733.png)

![image](https://cloud.githubusercontent.com/assets/413879/17076689/4116909e-50eb-11e6-9360-1f23096e3979.png)
