### ISSUE TITLE
Remove bower and grunt from deployment flow

### ISSUE THREAD

**Issue by notthetup** [webuildsg/webuild#240]
As per the discussion, it makes sense to avoid running tools designed to be run on development machine like `bower` and `grunt` on the server. It'll make deployment much simpler and hopefully slightly faster.

**Comment by sayanee** [comment]
hmmm the production server now has the the built file `/public/js/script.js` but still the browser console has the error like before:

```
script.js:2 Uncaught SyntaxError: Invalid or unexpected token
```

**Comment by sayanee** [comment]
How is the `bower install` and `grunt build` step triggered? With `package.json`'s `postinstall`? Shall we remove that from `package.json` and try it?

**Comment by sayanee** [comment]
Done list:

- [ ] commit the built js file `public/js/script.js`
- [ ] remove postinstall command for `bower install` and `grunt build` in `package.json`
- [ ] remove grunt and bower from dependencies in `package.json`

But still there's console error for:

![image](https://cloud.githubusercontent.com/assets/413879/15810178/af5b46f4-2bce-11e6-8735-137c612ce693.png)

**Comment by notthetup** [comment]
Very very weird

Same file with or without the redirect gives a different result. Smells like a cache issue.

![screenshot 2016-06-07 08 42 23](https://cloud.githubusercontent.com/assets/553140/15842464/de5a5f54-2c8b-11e6-85df-1c5a698249b4.jpg)
![screenshot 2016-06-07 08 42 27](https://cloud.githubusercontent.com/assets/553140/15842463/de56d168-2c8b-11e6-9f7a-eadab9c6fe56.jpg)

.

**Comment by notthetup** [comment]
Yup. Seems like cloudflare's auto-minification wasn't happy and was truncating the file. I turned it off. I've always hated that features.

![screenshot 2016-06-07 08 45 31](https://cloud.githubusercontent.com/assets/553140/15842534/56aa5716-2c8c-11e6-8f89-5d42e123e653.jpg)
