### ISSUE TITLE
add back auth0 js file

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#241]
file `public/js/vendor/auth0-widget.js/build/auth0-widget.min.js` for view `admin.pug`

**Comment by sayanee** [comment]
Trying to access https://webuild.sg/public/js/vendor/auth0-widget.js/build/auth0-widget.min.js and it gets redirected to https://webuild.sg. Cloudflare cache was purged as well.

**Comment by kahwee** [comment]
This works for me. https://webuild.sg/public/js/vendor/auth0-widget.js/build/auth0-widget.min.js shows a huge JS file.

**Comment by kahwee** [comment]
This works for me. https://webuild.sg/public/js/vendor/auth0-widget.js/build/auth0-widget.min.js shows a huge JS file.

**Comment by sayanee** [comment]
😂 😅 must be cache again. @kahwee can you also see the `Login` section on path `/admin`?

![image](https://cloud.githubusercontent.com/assets/413879/15916037/133de24a-2e21-11e6-9bd4-9d4b35531aed.png)

**Comment by sayanee** [comment]
ok it's working now 😝 

![image](https://cloud.githubusercontent.com/assets/413879/15989063/ae93842a-309c-11e6-95cb-8e0d98a1aa2a.png)
