### ISSUE TITLE
add a button for admin to easily remove events or groups

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#242]
The data is laid out in a table at `/admin`:

## New Groups

| Group ID | Group name | Group URL | Next event | Action |
| --- | --- | --- | --- | --- |
| 12345 | Hacker SG | URL | event, date | [remove group]() <br> [add group]()

## Upcoming 20 events

*These events are coming from added / approved groups*

| Event ID | Event name | Event URL | Action |
| --- | --- | --- | --- | 
| 12345 | Hacker SG June with description | URL | [remove event]()

**Comment by sayanee** [comment]
follow branch https://github.com/webuildsg/webuild/tree/admin-page

**Comment by notthetup** [comment]
This should be behind http basic-auth on the `/admin` endpoint.

Steps for setting up basic-auth.

1. redirect `/admin` coming over `http` to `https`.
2. If the `req` doesn't contain any basic auth information, reply with  "HTTP 401 Unauthorized" status and a WWW-Authenticate field : `WWW-Authenticate: Basic realm="User Visible Realm"`
3. If `req` does contain basic auth fields, then verify against environmental variables and respond with html if successful and  "HTTP 401 Unauthorized" status and a WWW-Authenticate field if not.

4. Rinse lather and repeat for all endpoints which update the black/white list.

**Comment by sayanee** [comment]
Currently on staging, without any save button. Just showing the list:

![image](https://cloud.githubusercontent.com/assets/413879/16473794/2f8edb10-3ea3-11e6-8c90-b59d82660c4e.png)

**Comment by sayanee** [comment]
@notthetup redirection is already there thanks to Cloudflare:

![image](https://cloud.githubusercontent.com/assets/413879/16474312/538cff6a-3ea8-11e6-8b2e-4a494fcd23fe.png)

**Comment by sayanee** [comment]
Staging design refactoring:

![image](https://cloud.githubusercontent.com/assets/413879/16477989/3f25748c-3ec9-11e6-865b-4ad5e56b0f7e.png)

**Comment by sayanee** [comment]
use [fetch](https://github.com/github/fetch) for post request

**Comment by sayanee** [comment]
use `.push()` synchronously in the `forEach` loop:

https://firebase.google.com/docs/database/server/save-data
