### ISSUE TITLE
upgrade Auth0

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#256]
[Email sent](https://mail.google.com/mail/u/0/#inbox/156000dffe4959a8)

![image](https://cloud.githubusercontent.com/assets/413879/16937703/e0e80ddc-4da3-11e6-9e2d-259158916381.png)

**Comment by sayanee** [comment]
- [Migrations](https://auth0.com/docs/migrations)
- [Call an Identity Provider API](https://auth0.com/docs/what-to-do-once-the-user-is-logged-in/calling-an-external-idp-api)
- [Identity Provider Access Tokens](https://auth0.com/docs/tokens/idp)

**Comment by notthetup** [comment]
This shouldn't affect our usecase.
