### ISSUE TITLE
countdown and date checker not working in Safari browser

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#259]
Related to #228

`fetch` polyfill in Safari is broken. See https://github.com/github/fetch/issues/303 and http://caniuse.com/#search=fetch

![image](https://cloud.githubusercontent.com/assets/413879/17216374/f5dd11f8-5512-11e6-9910-b2004c6fda8c.png)

**Comment by cheeaun** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest 👍

**Comment by cheeaun** [comment]
😢

**Comment by sayanee** [comment]
Part of proud history 😘 etched in the git commits 🗞https://github.com/webuildsg/webuild/issues/247 ⭐ 🎉 never to bo forgotten 🚀
