### ISSUE TITLE
Change group URL for KopiJS

### ISSUE THREAD

**Issue by cheeaun** [webuildsg/webuild#277]
I'm not sure how long this bug has been there but oh well...

So `group_url` needs to be `kopijs.org` instead of `kopi.io`.

The API call:
![screen shot 2017-02-28 at 2 45 04 pm](https://cloud.githubusercontent.com/assets/2296/23394792/fb1e9a72-fdc5-11e6-92e2-da1813190449.png)

The calendar:
![screen shot 2017-02-28 at 2 47 15 pm](https://cloud.githubusercontent.com/assets/2296/23394815/13d5ea02-fdc6-11e6-87c3-88a53e9cdb82.png)

**Comment by sayanee** [comment]
🤗 Thanks for noting this! Fixed in firebase DB. Please re-open again if the wrong URL persists 💯 

![image](https://cloud.githubusercontent.com/assets/413879/23410236/79ebbedc-fe09-11e6-9de7-659c7d6a5608.png)
