### ISSUE TITLE
Check Facebook authentication

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#291]
## Steps to reproduce the error

1. Go to [admin page](https://webuild.sg/admin)
1. Click login with Facebook

    ![image](https://user-images.githubusercontent.com/413879/28602263-ab411f4a-71ef-11e7-8e01-9846edc23fcb.png)
1. View the errors

<img width="564" alt="screenshot 2017-07-26 10 40 35" src="https://user-images.githubusercontent.com/413879/28602240-8af21b0e-71ef-11e7-9ef4-4013ff452d80.png">
<img width="483" alt="screenshot 2017-07-26 10 40 48" src="https://user-images.githubusercontent.com/413879/28602242-8caa0614-71ef-11e7-980d-19fae0494ba4.png">

**Comment by notthetup** [comment]
Fixed by not requesting "user_groups" permissions on Auth0 side.
