### ISSUE TITLE
Show events that are currently occurring

### ISSUE THREAD

**Issue by alyssaq** [webuildsg/webuild#75]
* Old events including currently-occurring events are removed.
* Useful to show for latecomers.

**Comment by alyssaq** [comment]
Completed in 0e83e392c4e0615543755df0fb000f49a59ab819

**Comment by sayanee** [comment]
:+1: this is only for the whitelist events excluding facebook / eventbrite and meetup.com right?

**Comment by sayanee** [comment]
Also should we show an `ongoing` label beside events with `end_time` shown to avoid confusion?

**Comment by alyssaq** [comment]
Yep,  only for whitelisted events. Hmm,  I have noticed that some events do not have an end time and default to 2 hours duration.
I'm sure people can see that it's currently occurring. It would be nice to highlight today's events.

**Comment by sayanee** [comment]
yes by default we put `end_time` to `+2` if none is there. Maybe we can store the on-going events in memory before the cron kicks and then add them at the end.

i was testing the UI just now and for multi-days long hackathon-like events showing an event yesterday might coz confusion unless we put an `ongoing` label with `end_time` displayed. Something to brainstorm :smile:

**Comment by sayanee** [comment]
closed due to inactivity. feel free to open with a pull request additions to the code base.
